### ISSUE TITLE
Need permission to set up the CI environment

### ISSUE THREAD

**Issue by jcs090218** [game-ci/unity-license-activate#69]
I have recently set up the CI for this tool but would need permission to set the environment variables to make the workflow work.

I will need two variables for `EMAIL` and `PASSWORD`.

https://github.com/game-ci/unity-license-activate/blob/7126002f95e45fbbd60a44730d1a8b160b7dffe2/.github/workflows/test.yml#L27

cc @webbertakken

**Comment by webbertakken** [comment]
I have given you Maintainer status for this repo. Does it help?

**Comment by jcs090218** [comment]
Nope, I can now see the `Settings` tab but couldn't see `Actions` button on the left.

![Image 1](https://user-images.githubusercontent.com/8685505/203474709-27121d3f-74a9-4699-b012-7cb6d8f13a07.png)

This is what I see now.

**Comment by webbertakken** [comment]
I see. Provided you with full admin for this repo.

**Comment by jcs090218** [comment]
Awesome! Thanks!
